ci: get rid of -Wno-error (#17)
* ci: build elfutils without -Wno-error with clang

* ci: -Wno-error=xor-used-as-pow

https://sourceware.org/pipermail/elfutils-devel/2021q1/003538.html

* ci: -Wno-error=gnu-variable-sized-type-not-at-end

```
lang -D_GNU_SOURCE -DHAVE_CONFIG_H -DLOCALEDIR='"/usr/local/share/locale"' -I. -I..  -I. -I. -I../lib -I.. -I../libelf -I../libebl -I../libdw -I../libdwelf  -std=gnu99 -Wall -Wshadow -Wformat=2 -Wold-style-definition -Wstrict-prototypes    -Wnull-dereference -Wimplicit-fallthrough -Werror -Wunused -Wextra    -D_FORTIFY_SOURCE=2 -g -O2 -fno-addrsig -Wno-error=xor-used-as-pow -MT asm_newscn_ingrp.o -MD -MP -MF .deps/asm_newscn_ingrp.Tpo -c -o asm_newscn_ingrp.o asm_newscn_ingrp.c
asm_newscn.c:49:22: error: field 'pattern' with variable sized type 'struct FillPattern' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
  struct FillPattern pattern;
                     ^
1 error generated.
```

* ci: -Wno-error=unused-const-variable

* ci: drop -Wno-error in the CLANG_ASAN_UBSAN stage as well